### ISSUE TITLE
Making the online doc responsive (mobile-friendly)

### ISSUE THREAD

**Issue by lum-supakorn** [JSBSim-Team/jsbsim-reference-manual#10]
Hello, all.

I'm looking to help make the JSBSim online documentation a little more mobile friendly. As of now, the content does not look right when viewed on a phone (e.g. the menu does not collapse, and there is very little spacing between it and the content).

Do you have any suggestions for a documentation theme that comes responsive out-of-the-box? If not I might consider writing a new one.

**Comment by agodemar** [comment]
@lum-supakorn thanks for being available to help. 
The documentation layout has been basically my first attempt with the Github Pages framework. I did some extra work on a baseline theme to customize the menu but did not consider optimizing the content for mobile devices.
If you are willing help by developing a responsive layout it would be great.

**Comment by lum-supakorn** [comment]
Thank you for your reply. I’ll see what I can help with.

**Comment by bcoconni** [comment]
@lum-supakorn 
I have submitted the PR #13 to make the docs responsive: check at https://bcoconni.github.io/jsbsim-reference-manual/

**Comment by agodemar** [comment]
The new responsive version looks great to me. Thanks!
