### ISSUE TITLE
Abandoning Jekyll and using something else?

### ISSUE THREAD

**Issue by LuFlo** [JSBSim-Team/jsbsim-reference-manual#22]
@agodemar proposed in another issue to maybe use Docusaurus https://github.com/JSBSim-Team/jsbsim/discussions/638#discussioncomment-2887152

I personally would prefer using a pure "builder", also I don't think we need a react single page application for a documentation site. Maybe something like [MkDocs](https://www.mkdocs.org/) would be enough? On the other hand I also don't have much experience with github pages, so take my suggestions with a grain of salt.

**Comment by seanmcleod** [comment]
Only had a very brief look at MkDocs, but it looks nice and simple, especially in terms of setup, just a python module via pip install. Did see references to it support github pages.

**Comment by agodemar** [comment]
I like MkDocs. It's definitely worth trying it out
