### ISSUE TITLE
Section Quickstart -> "Building the program and the library"

### ISSUE THREAD

**Issue by agodemar** [JSBSim-Team/jsbsim-reference-manual#3]
Referring to [this issue in jsbsim development](https://github.com/JSBSim-Team/jsbsim/issues/9), I propose to address the [related section in the manual](https://jsbsim-team.github.io/jsbsim-reference-manual/mypages/building-the-program/).

JSBSim now relies on CMake so we should document it accordingly.

**Comment by bcoconni** [comment]
Done !
Let me know if something is missing or unclear.
