### ISSUE TITLE
Deployment fix for MkDocs

### ISSUE THREAD

**Issue by bhoffpauir** [JSBSim-Team/jsbsim-reference-manual#30]
Hello JSBSim Team,

I noticed that the new deployment of the reference manual after my pull request #29 is bugged.  I think that changes are needed to the **Pages** menu of the repository settings.

In my fork, which deploys successfully, I have the following configuration:

![image](https://github.com/JSBSim-Team/jsbsim-reference-manual/assets/56570654/a2acbca5-393d-4a51-a980-61c1e6890432)

After testing in a different fork of the reference manual, I discovered that you need to  deploy the site manually at first with the following command:
```bash
$ # At the root of the repository in the master branch:
$ mkdocs gh-deploy --force
```
After that, the **gh-pages** branch will be created and can be set in the **Pages** menu in the settings.  After this the GitHub workflow will take effect and redeploy the site automatically upon any further pushes to the **master** branch.

Relevant documentation:
- [GitHub Pages publishing sources](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch)
- [Deploying Your Docs - MkDocs](https://www.mkdocs.org/user-guide/deploying-your-docs/)
- [Publishing your site - Material for MkDocs](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch)

Also, could you please add environment variables (Settings -> Code and automation -> Environments -> github pages -> Environment variables) named `CI` and `OFFLINE` with the values shown below.  It may be useful for any future changes that are made to the *mkdocs.yml* config.  Such as enabling/disabling certain feature or plugins for offline builds of the documentation.

![image](https://github.com/JSBSim-Team/jsbsim-reference-manual/assets/56570654/fe660d0b-2e9e-4c87-a654-23d1f1c1ef81)

Sorry for the inconvenience, but I think this will fix the problem.

Thanks,
Brian

**Comment by bhoffpauir** [comment]
@bcoconni

**Comment by bcoconni** [comment]
Hi @cppimmo, thanks for the heads up.
I'll look into this.

**Comment by bcoconni** [comment]
Hi @cppimmo, I followed your instructions but it seems it is not the correct page that is displayed at https://jsbsim-team.github.io/jsbsim-reference-manual/

The command `` has been run and [has reported a few warnings](https://github.com/JSBSim-Team/jsbsim-reference-manual/actions/runs/5690999914/job/15425964227#step:7:1), I am not sure if they are relevant for the problem.

**Comment by bhoffpauir** [comment]
Hello @bcoconni, I looked at the output generated in the **gh-pages** branch of this repository and it seems correct.  However, the HTML that is present in the deployment seems to only be some left overs from Jekyll.  I think it may be necessary to the run the `mkdocs gh-deploy --force` command once manually at the root of the repository.

The `mkdocs gh-deploy --force` command is present in workflow file, but it should result in a new action named "pages-build-deployment" being created.  In this repository I can only see the "ci" action.  You can see how this looks [in my fork](https://github.com/cppimmo/jsbsim-reference-manual/actions/workflows/pages/pages-build-deployment).

**Comment by bcoconni** [comment]
So I have modified the CI workflow (commit fc54a14af4317045433c7102faa18cab89ddab4a) to deploy the GitHub pages via GitHub workflows rather than relying on `mkdocs` for that.

As far as I can see, the website is now displaying the correct documentation.

**Comment by bhoffpauir** [comment]
Hello @bcoconni, that is awesome.  It does look correct.  I'll go ahead and close this issue.
